language: node_js
node_js:
  - 8
  - 6
  - 4
os:
  - linux
  - osx
branches:
  only:
    - master
    - /^greenkeeper.*$/
git:
  depth: 999
before_install:
  - if [[ `npm -v` < 5* ]]; then npm install -g npm@5; fi
script:
  - npm run test
env:
  - BUILD_LEADER_ID=7
jobs:
  include:
    - stage: release
      node_js: 8
      os: linux
      script: npm run test
      after_success: 
        - if [ -n "${CODECOV_TOKEN:-}" ]; then npm run codecov; fi
        - npm run semantic-release